### ISSUE TITLE
Gerber file for JLCPCB

### ISSUE THREAD

**Issue by sean-skt** [codmpm/a1200-led-pcb#2]
Hi there,

I was wondering if it were possible to create a ZIP file with a gerber of this PCB so that it can be uploaded to JLCPCB with all the appropriate specifications for them to manufacture it, such as the size of the board.. At the moment when I upload it them it doesn't seem to register even though the website says it has been uploaded. No picture of the board comes up like others that I have had made.

Thanks for that. Kind regards.

**Comment by codmpm** [comment]
Hey Sean,

the gerbes heavily depend on the boardhouse you are using. We had good experience with aisler in europe and oshpark in the US who ship worldwilde. All of them simply accept the .brd file.

Otherwise you can use the cam template from jlcpcb with eagles cam processor: 
https://support.jlcpcb.com/article/137-how-to-generate-gerber-and-drill-files-in-autodesk-eagle

See attached the gerber.zip which was created with [jlcpcb_2_layer_v9.cam](https://raw.githubusercontent.com/JLCPCBofficial/jlcpcb-eagle/master/cam/jlcpcb_2_layer_v9.cam). Uploaded fine for me.
![Bildschirmfoto 2022-04-11 um 14 45 12](https://user-images.githubusercontent.com/9745239/162742073-b6c19246-4a96-4457-ba1f-9ca250634fb0.png)
[a1200-led_2022-04-11.gerber.zip](https://github.com/codmpm/a1200-led-pcb/files/8464137/a1200-led_2022-04-11.gerber.zip)

**Comment by sean-skt** [comment]
Awesome! Thanks so much for that, really appreciate it.
